# config.yml
git:
  paging:
    useconfig: false
    colorArg: always
    pager: diff-so-fancy
gui:
  expandFocusedSidePanel: true
  sidePanelWidth: 0.25
merge:
  tool: nvim
mergetool:
  nvim:
    cmd: nvim -f -c "Gdiffsplit!" "$MERGED"
  prompt: false
